DOC Add release process instructions
pyodide/pyodide pull request #1533
Opened 2021-04-22 20:43 UTC by rth

This adds some documentation on how to make a release. Please let me know if you have any comments or questions.

I also moved the "Contributing to the “core” C Code" page under the "Contributing" page in the left side bar.

2021-04-26 14:38 UTC, phorward requested changes
Hello @rth,
thank you very much for writing down this detailed guide on creating a release. I found just two little mistakes, after that we can merge. Maybe some steps could also be put into some kind of shell script later, e.g. updating the contributors list.

2021-04-26 14:38 UTC, phorward commented on docs/development/contributing.md
> +For information regaring making releases see {ref}`maintainer-information`.
"regarding to making a release, see"?

2021-04-26 14:38 UTC, phorward commented on docs/development/maintainers.md
> +For the minor release commits need to be added to the `stable` branch, ideally via a PR.
"For the minor release, commits" <-- just add the comma

2021-04-26 19:29 UTC, rth commented
Thanks @phorward, I addressed you comment.

2021-04-27 07:42 UTC, phorward approved these changes

2021-04-28 17:28 UTC, merged