DOC Improve the documentation home page
pyodide/pyodide pull request #1958
Opened 2021-11-14 11:32 UTC by rth

Partially addresses https://github.com/pyodide/pyodide/discussions/1954

Add more relevant information to the documentation home page and decrease the depth of the Using pyodide TOC otherwise it generates too many links (particularly for the FAQ)

2021-11-14 20:56 UTC, phorward requested changes
Hi @rth thanks for the improving, can you please re-check the suggestions?

2021-11-14 20:56 UTC, phorward commented on README.md
> +- Blog : [blog.pyodide.org](https://blog.pyodide.org/)
```suggestion
- Blog: [blog.pyodide.org](https://blog.pyodide.org/)
```

2021-11-14 20:56 UTC, phorward commented on docs/index.rst
> +Pyodide brings the Python 3.9 runtime to the browser via WebAssembly thanks to
```suggestion
Pyodide brings the Python 3.9 runtime to the browser via WebAssembly, thanks to
```

2021-11-14 20:56 UTC, phorward commented on docs/index.rst
> +It builds Python scientific stack including NumPy, Pandas, Matplotlib, SciPy, and
```suggestion
It builds the Python scientific stack including NumPy, Pandas, Matplotlib, SciPy, and
```

2021-11-14 20:56 UTC, phorward commented on docs/index.rst
> +scikit-learn. Over 75 packages are currently available. In addition, it's
```suggestion
scikit-learn. Over 75 packages are currently available. In addition, its
```

2021-11-14 20:56 UTC, phorward commented on docs/index.rst
> +Pyodide development happens on Github: `github.com/pyodide/pyodide <https://github.com/pyodide/pyodide>`_
```suggestion
Pyodide development happens on GitHub: `github.com/pyodide/pyodide <https://github.com/pyodide/pyodide>`_
```

2021-11-14 20:56 UTC, phorward commented on docs/index.rst
> +- Blog : `blog.pyodide.org <https://blog.pyodide.org/>`_
```suggestion
- Blog: `blog.pyodide.org <https://blog.pyodide.org/>`_
```

2021-11-14 20:56 UTC, phorward commented on docs/project/about.md
> +- Blog : [blog.pyodide.org](https://blog.pyodide.org/)
```suggestion
- Blog: [blog.pyodide.org](https://blog.pyodide.org/)
```

2021-11-14 22:32 UTC, rth commented on docs/index.rst
> +scikit-learn. Over 75 packages are currently available. In addition, it's
That one was  correct: "it is possible"

2021-11-14 22:33 UTC, rth commented
Thanks for the review @phorward !

2021-11-15 09:28 UTC, phorward approved these changes

2021-11-15 09:31 UTC, merged