Add tree-sitter-java, tree-sitter-go, tree-sitter-python
pyodide/pyodide pull request #5102
Opened 2024-10-07 18:33 UTC by ericwb

This is a follow-on to PR #5099 which added the dependency of tree-sitter to the packages.

This change adds tree-sitter-java, tree-sitter-go, tree-sitter-python packages and respective unit tests. Java, Go, and Python are popular languages, so its useful to add these grammars so a user can parse source code in those languages.

### Description

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

2024-10-07 19:14 UTC, hoodmane approved these changes
Cool! Thanks @ericwb.

2024-10-07 20:58 UTC, ericwb commented
Looks like the build is failing due to not finding the dependent tree-sitter C header files. @hoodmane Any tips on how to resolve this. Sorry, I'm pretty new to pyodide's build environment.

2024-10-07 21:08 UTC, hoodmane commented
Doing a basic build only produces a wheel, it won't install any headers or libs. So if downstream packages need to compile/link against tree-sitter, there will need to be a build script to install those into `$WASM_LIBRARY_DIR`. I'll take a look into it tomorrow if you don't figure it out.

2024-10-07 22:58 UTC, agriyakhetarpal requested changes
Thanks, @ericwb!

2024-10-07 22:58 UTC, agriyakhetarpal commented on packages/tree-sitter-go/.DS_Store
Could you please remove this binary file, @ericwb?

2024-10-07 22:58 UTC, agriyakhetarpal commented on packages/tree-sitter-java/.DS_Store
and this one

2024-10-07 22:58 UTC, agriyakhetarpal commented on packages/tree-sitter-python/.DS_Store
and this one – it might be worth adding this to our `.gitignore` file, too.

2024-10-08 09:07 UTC, hoodmane commented
The problem is that the sdists don't contain the headers, so building from them won't work. I made some PRs to fix.
https://github.com/tree-sitter/tree-sitter-java/pull/188
https://github.com/tree-sitter/tree-sitter-go/pull/151
https://github.com/tree-sitter/tree-sitter-python/pull/285

For now, we should pull them in from github which does have the headers.

@henryiii tree-sitter does its builds with cibuildwheel, hypothetically it seems like it would be nice if cibuildwheel would build the wheel from the sdist so that if necessary files are missing from the sdist it would notice. But perhaps there's a good reason not to do that? Or it's supposed to work that way but it didn't function properly in this case?

2024-10-21 13:49 UTC, agriyakhetarpal commented
`cibuildwheel` can already build from an sdist just fine – one just needs to pass the path to the tarball in `package-dir:` if using the GitHub Action, or as a positional argument if using the CLI. I think more projects should adopt this approach. Henry's https://github.com/henryiii/check-sdist tool is quite useful, too.

2024-10-21 14:33 UTC, merged