Fix PyXiRR build regression due to Maturin 1.8
pyodide/pyodide pull request #5283
Opened 2024-12-30 12:00 UTC by agriyakhetarpal

### Description

Through https://github.com/PyO3/maturin/pull/2391 via the recently released [Maturin version 1.8.0](https://github.com/PyO3/maturin/releases/tag/v1.8.0), builds for PyXiRR (added in #4513) have been failing.

I've applied this PR, which I submitted upstream: https://github.com/Anexen/pyxirr/pull/64, as a patch here, which can be dropped later. Tagging @Anexen as the listed recipe maintainer for visibility.

### Checklists

N/A

2024-12-30 12:31 UTC, agriyakhetarpal commented
Ah, `orjson` has the same problem, for which they've released a new version already: https://github.com/ijl/orjson/releases/tag/3.10.13

2024-12-30 13:52 UTC, spicy-sauce approved these changes

2024-12-30 13:55 UTC, spicy-sauce requested changes
check why the circleci checks fail...

2024-12-30 14:00 UTC, hoodmane commented
```
💥 maturin failed                                                               
  Caused by: `project.version` field is required in pyproject.toml unless it is 
present in the `project.dynamic` list                                           
Error: command ['maturin', 'pep517', 'build-wheel', '-i',                       
'/tmp/build-env-8rechu2o/bin/python', '--compatibility', 'off'] returned        
non-zero exit status 1
```

2024-12-30 14:16 UTC, agriyakhetarpal commented
Ah, now `cramjam` has the same error. I guess I will need to to do this for all Maturin-based packages.

2024-12-30 14:23 UTC, agriyakhetarpal commented
Submitted a PR to `cramjam` here: https://github.com/milesgranger/cramjam/pull/196

2024-12-30 14:28 UTC, agriyakhetarpal commented
Argh, we have 19 packages that require Rust/maturin...

2024-12-30 14:48 UTC, agriyakhetarpal commented
A short, internal tracker:

| Package | Affected? |
|--------|--------|
| bcrypt | No, it specifies a version and doesn't use `maturin` |
| cbor-diag | Yes |
| clarabel | Yes |
| cramjam | Will be fixed via https://github.com/milesgranger/cramjam/pull/196 and updated here |
| cryptography | No |
| lakers-python | Yes |
| libcst | No, uses `setuptools-rust` |
| nh3 | Yes |
| orjson | Yes, fixed here via https://github.com/ijl/orjson/releases/tag/3.10.13 |
| pyxel | Yes, fixed via https://github.com/kitao/pyxel/releases/tag/v2.2.10 and updated here |
| pyxirr | Yes, will be fixed via https://github.com/Anexen/pyxirr/pull/64 and updated here  |
| rateslib | No |
| river | No |
| rpds-py | Yes |
| rust-abi-test | No |
| rust-panic-test | No |
| sourmash | No |
| tiktoken | No |
| river | No |

2024-12-30 15:23 UTC, hoodmane commented
In the meantime can we cap maturin?

2024-12-30 16:08 UTC, agriyakhetarpal commented
Yes, makes sense to me!

2025-01-06 12:00 UTC, ryanking13 commented
Thanks for handling this issue!

2026-07-29 07:31 UTC, closed without merging